apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: user-service
          image: ghcr.io/maxbpro/docker.io/library/soulmate-api-gateway:1.0.0
          ports:
            - containerPort: 8080